inc/GenInfo.hh
inc/TrkInfo.hh
src/InfoMCStructHelper.cc

We want to standardize momentum as a scalar quantity in TrkAna. This PR implements the necessary changes for the MC branches (the reco branches already have momentum as a scalar quantity). All *.momx, *.momy, and *,momz branches have been replaced by *.mom, *.costh, *.phi.
Here is the list of leaf changes in the trkana tree created by TrkAnaReco.fcl:
- momentum of `StepPointMC` at entrance, middle and exit of tracker:
- `demcent.momx`, `demcent.momy`, `demcent.momz` -> `demcent.mom`, `demcent.costh`, `demcent.phi`
- `demcmid.momx`, `demcmid.momy`, `demcmid.momz` -> `demcmid.mom`, `demcmid.costh`, `demcmid.phi`
- `demcxit.momx`, `demcxit.momy`, `demcxit.momz` -> `demcxit.mom`, `demcxit.costh`, `demcxit.phi`
- momentum of `GenParticle`:
- `demcgen.momx`, `demcgen.momy`, `demcgen.momz` -> …

Make momentum a scalar quantity, and add direction vector

---

fcl/TrkAnaReco_ceSimReco.fcl

A few times people have tried to use TrkAnaReco.fcl with the output of ceSimReco.fcl. Unfortuntaely, it doesn't work because ceSimReco.fcl only runs the downstream e-minus reconstruction. In this PR I have added a fcl file for use with the output of ceSimReco. This will be ideal for students who might be asked to run ceSimReco as a first task to get used to the code.

Adding fcl file for use with output of ceSimReco

---

fcl/prolog.fcl
inc/CaloClusterInfoMC.hh
inc/GenInfo.hh
inc/InfoMCStructHelper.hh
inc/InfoStructHelper.hh
inc/Names.hh
inc/SimInfo.hh
inc/TrkCaloHitInfo.hh
inc/TrkInfo.hh
inc/TrkStrawHitInfo.hh
inc/TrkStrawHitInfoMC.hh
src/InfoMCStructHelper.cc
src/InfoStructHelper.cc
src/Names.cc
src/TrkAnaTreeMaker_module.cc

I went a bit further with adding genealogy information than the original PR so here is an updated message:
In this PR I have added the ability to configure the depth of the MC genealogy that is stored in the trkana tree. The new branches are:
- `demsim` : MC information for the particle that created the track
- `demcparent`: MC information for the parent of the particle that created the track
- `demcgparent`: MC information for the grandparent of the particle that created the track
- `demcggparent`: MC information for the great-grandparent of the particle that created the track
- additional levels insert an extra `g` in the branch name
This PR also remove the `demcgen` branch
The depth of the genealogy is set to 5 by default for the candidate branch (`de`). MC information for the …

Updated Genealogy Info

---

src/InfoMCStructHelper.cc

can be merged now, but ideally wait until after Mu2e/Offline#680 is merged, to switch only after final tweaks.

move to new ParticleDataList

---

fcl/prolog.fcl

This was breaking TrkAnaReco.fcl and generate_fcl

Fix prolog.fcl which was referring to modules we've removed

---

fcl/CrvExpert.fcl
fcl/TrkAnaReco.fcl
fcl/TrkAnaReco_wTrkQualFilter.fcl
fcl/prolog.fcl
src/TrkAnaTreeMaker_module.cc

This PR makes some changes to the CRV-related branches in TrkAna. 
List of changes:
- branches ```crvinfo```, ```crvinfomc```, ```crvsummary```, ```crvummarymc```, and ```crvinfomcplane``` are now hidden behind ```FillCRVHits``` fhicl parameter
- these are now turned off by default in TrkAnaReco.fcl
-  new CrvExpert.fcl shows how to generate these branches
- ```bestcrv``` branch is no longer an integer corresponding to an element in the ```crvinfo``` array but a ```CrvInfoReco``` struct
- i.e. ROOT cut ```crvinfo[bestcrv]._timeWindowStart>-80``` is now ```bestcrv._timeWindowStart>-80```
- new ```bestcrvmc``` branch contains the ```CrvInfoMC``` equivalent information
- fhicl parameters ```AnalyzerCRV*``` have been renamed to ```FillCRV*``` for consistency with other fhicl parameters in …

CRV-related Changes

---

inc/TrkInfo.hh
src/InfoMCStructHelper.cc
src/InfoStructHelper.cc
src/SConscript

Hi Everyone. This PR removes the helix parameterizations from the TrkAna trees. The leaves used from these branches have been stand-ins for things like cosmic-ray rejection based on track extrapolation. For the time being I have kept individual leaves for ```d0```, ```td```, and ```maxr``` while we implement a module that performs such algorithms.

Remove Helix Parameters

---

examples/pandas-example.py
src/TrkAnaTreeMaker_module.cc

Hi Everyone! I was having issues accessing some of the leaves with uproot+pandas. For example, the branch ```de.t0``` was accessed with ```df["t0"]```, which could also be confused with ```ue.t0```.
It turns out that if we add a period to the branch name when we create the trkana tree, we can then access ```df["de.t0"]```, which is a nicer interface. I have added an example using pandas to the ```examples/``` directory. This should have no effect on any ROOT scripts but let me know if it causes issues.

Nicer python interface

---

inc/EventWeightInfo.hh
inc/RecoQualInfo.hh
src/BestCrvHitDeltaT_module.cc
src/TrkAnaTreeMaker_module.cc

Hi Everyone,
This PR contains two changes. One is a simple bug fix in commit 70c74eb, as reported by the CRV group. The other is a continuation of PR #53, which resolves an issue when importing TrkAna trees to python. 
The issue is that branches like ```dequal.TrkQual``` gets imported as ```df["TrkQuals"]```, which would then clash with ```uequal.TrkQual```.
One complication with the branches fixed in this PR is that their leaf names are dynamic for flexibility. For example we want the ```evtwt``` branch to read out any ```EventWeight``` object created by the user. This means the solution in PR #53 (to put a period at the end of the branch name and let ROOT name the leaves) does not work here.
The solution I settled on is to create a new branch for each dynamic leaf. This fixes the issue …

Nicer Python Interface + BestCRV bug fix

---

fcl/TrkAnaReco_addStopTgtVDs.fcl
fcl/prolog.fcl
inc/InfoMCStructHelper.hh
src/InfoMCStructHelper.cc
src/TrkAnaTreeMaker_module.cc

Hi everyone,
This PR adds a new feature to TrkAna: fcl-configurable virtual detector IDs. 
You can now define new branches with any virtual detector ID you like. TrkAna will create a reco and an MC branch. See the example fcl/TrkAnaReco_addStopTgtVDs.fcl for a bit more information. At the moment, this example only produces the correct output for the MC branch:
```
trkana->Scan("sqrt(demcpri.mom.mag2()):sqrt(demctgt.mom.mag2()):sqrt(demcent.mom.mag2())")
************************************************
*    Row   * sqrt(demc * sqrt(demc * sqrt(demc *
************************************************
*        0 * 104.97261 * 104.80454 * 104.66930 *
*        1 * 104.97260 * 104.67928 * 104.30360 *
*        2 * 104.97261 * 104.86999 * 104.52937 *
*        3 * 104.97261 * 104.93677 * 104.62403 …
```

Add ability to configure virtual detectors in TrkAna

---

inc/TrkStrawHitInfo.hh
src/InfoStructHelper.cc

This PR removes the use of the helix() function from the main processing, as that can fail when the reco track axis is near the z axis.  It also adds some flags.  The TrkPid function needs a complete rewrite.

Small Fixes

---

src/BestCrvHitDeltaT_module.cc
src/InfoMCStructHelper.cc

Check for invalid artPtrs to SimParticles in CrvCoincidenceClusterMCs caused by noise hits.

Check for invalid artPtrs to SimParticles in CrvCoincidenceClusterMCs

---

fcl/TrkAnaReco_multipleBestCrv_differentThresholds.fcl
fcl/prolog.fcl

This PR goes with Mu2e/Offline#973 and Mu2e/Production#244 and updates the default module labels used by TrkAna for the CrvCoincidenceCollections. In addition, there is also an example fcl for having multiple ```bestcrv``` branches from different CrvCoincidenceCollections

Allow for Multiple CrvCoincidenceCollections

---

fcl/TrkAnaReco.fcl
fcl/TrkAnaReco_multipleBestCrv_differentThresholds.fcl
fcl/prolog.fcl
inc/BestCrvAssns.hh
src/MakeCrvCoincidenceClusterMCAssns_module.cc
src/TrkAnaTreeMaker_module.cc

Following on from #82 and associated PRs, Yuri noticed that the ```bestcrvmc``` branch can only get data from a single ```CrvCoincidenceClusterMCCollection```.
The solution I found is to create a single Assns to associate reco to MC CrvCoincidenceClusters and use that in TrkAna. The Assns is created in a new module (```MakeCrvCoincidenceClusterMCAssns```)

Allow bestcrvmc to come from different collections

---

inc/RecoQualInfo.hh

The whole e28 compiler warning message (uninitialized variables, fixed by this PR) follows.  There are probably other ways to fix it.
> In file included from /cvmfs/mu2e.opensciencegrid.org/artexternals/gcc/v13_1_0/Linux64bit+3.10-2.17/include/c++/13.1.0/bits/stl_iterator.h:85,
>                  from /cvmfs/mu2e.opensciencegrid.org/artexternals/gcc/v13_1_0/Linux64bit+3.10-2.17/include/c++/13.1.0/bits/stl_algobase.h:67,
>                  from /cvmfs/mu2e.opensciencegrid.org/artexternals/gcc/v13_1_0/Linux64bit+3.10-2.17/include/c++/13.1.0/bits/stl_tree.h:63,
>                  from /cvmfs/mu2e.opensciencegrid.org/artexternals/gcc/v13_1_0/Linux64bit+3.10-2.17/include/c++/13.1.0/set:62,
>                  from ./Offline/GeneralUtilities/inc/ParameterSetHelpers.hh:16,
>                  from …

add init due to e28 warning

---

src/InfoStructHelper.cc

The existing calculation NDOF=nactive-nparams was wrong for KinKal fits, as noted.  The fix requires an upgrade to KalSeed, which is in Offline PR 1072, thus this PR is tied to that.
Note that the NDOF value recorded in existing mcs (reco) MDC2020 output files is wrong, and requires a reprocessing to fix.  The fit consistency value however was calculated using the correct NDOF.  On general grounds we should encourage analyzers to switch to fitconsistency over chisq/NDOF in analysis anways.

Fix NDOF calculation

---

example-analysis-scripts/Genealogy.C
example-analysis-scripts/Genealogy.py
src/InfoMCStructHelper.cc

This PR updates the ```demmcsim``` branch again. Instead of a ```generation``` leaf, we now have two leaves that store ```MCRelationships```: the relationship to the track primary (the particle that created the track) is called ```trkrel```, and the relationship to the event primary (the particle that we wanted to reconstruct) is called ```prirel```. These leaves have two members ```_rel``` for the relationship (defined in Offline/MCDataProducts/inc/MCRelationship.hh, and ```_rem``` the number of generations removed the particle is.
As an example, to look at the particle that generated the track:
```
trkana->Draw("demmcsim.mom.R()", "demmcsim.trkrel._rem==0")
```
to look at its parent, you can do:
```
trkana->Draw("demmcsim.mom.R()", "demmcsim.trkrel._rem==1")
```
etc.
You can also look …

Genealogy update

---

README.md
inc/SimInfo.hh
src/InfoMCStructHelper.cc
tutorial/README.md

It would be useful to have end information for the SimParticles and not just the start info (see Issue #109) so I've added it here. I've kept the names of the start position and momentum branches as ```mom``` and ```pos``` to avoid making a breaking change but I'm open to changing them to ```startmom``` and ```startpos``` for clarity

Add end information for SimParticles

---

fcl/TrkAnaExtracted.fcl
fcl/prolog_trigger.fcl
inc/EventInfo.hh
src/TrkAnaTreeMaker_module.cc

The existing branch names for protonabsorber etc. caused errors when creating an event loop class with MakeClass.

Fix branch structures.  Fix extracted script

---

validation/create_val_file.C

This validation script creates a ROOT file with some histograms generated from the TrkAna tree. The idea is that we create two files and use ```valCompare``` to compare the histograms in each file.
At the moment, this script covers a few variables in:
- event info and event info MC,
- the track fit at the entrance, middle, and exit of the tracker (also with a time cut)
- the momentum resolution of the fit (to test reco - MC matching)
- the calorimeter hit associated with the track
- some CRV variables,
- some MC genealogy
If there's anything major that this isn't covering, then let me know.

Create validation script

---

fcl/TrkAnaExtracted.fcl
fcl/TrkAnaReco.fcl
fcl/TrkAnaReco_wTrkQualFilter.fcl
fcl/prolog.fcl
fcl/prolog_trigger.fcl
inc/CrvHitInfoReco.hh
inc/CrvInfoHelper.hh
src/CrvInfoHelper.cc
src/TrkAnaTreeMaker_module.cc

1.  Updated CRV branch names (following discussion with Andy, Ralf, and Yuri): 
- `crvhit` —> `crvcoincs`;
- `crvpulseinfo` —> `crvpulses`;
- `crvwaveforminfo` —> `crvdigis`.
2. Added a new leaf to `crvcoincs` tree: `float PEsPerLayer[4]`. This is an array of photoelectron counts indexed by layer number (four layers per module), which is filled by looping through the reco pulses for each coincidence cluster. See [Mu2e-doc-47954](https://mu2e-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=47954). I don't see any change in the `TrkAna` run time with this additional `for` loop. 
3. As a side note, the original `PEs` leaf was changed from an `int` to a `float`, after discussing with Ralf and Yuri. The convention that `PEs` are integers is outdated.

Updated CRV branch names and added a PEs per layer variable. 

---

fcl/TrkAnaReco.fcl
fcl/TrkAnaReco_mergedKalSeeds.fcl
fcl/prolog.fcl
src/TrkAnaTreeMaker_module.cc

This PR updates TrkAna to use a collection of KalSeedPtrs rather than a collection of KalSeeds. This makes it easy to combine track collections into one and have a single branch for all tracks. I have added an example fcl configuration file (```TrkAnaReco_mergedKalSeeds.fcl```) that merges all KalSeeds into one collection and puts it all in one ```trk``` branch.
The behavior of TrkAnaReco.fcl hasn't changed. In order to support both one branch and multiple branches, I have added ```MergeKalSeeds``` modules that "merge" a single KalSeedCollection to get a KalSeedPtrCollection. I have validated TrkAnaReco.fcl with the validation script before and after making changes and the histograms are identical as reported by ```valCompare```

Update to use KalSeedPtrs and add example of using a merged track collection

---

fcl/TrkAnaTriggerMC.fcl
fcl/prolog_trigger.fcl
inc/HelixInfo.hh
src/InfoStructHelper.cc

This fix relies on Offline PR 1267, which is now merged.  For now I've kept the structure that this script creates 2 TTrees (tpr and cpr), but given the indirection afforded by the Ptr collection these can now be combined into a single tree, which I'll do in a separate PR.  That PR will also add the new Apr and Mpr trigger paths.

Migrate trigger script to ptr-based collections

---

fcl/TrkAnaReco_ceSimReco.fcl

This hadn't been updated for v5

Fix for fcl that runs on ceSimReco output

---

inc/TrkStrawHitInfo.hh
inc/TrkStrawHitInfoMC.hh
src/InfoMCStructHelper.cc
src/InfoStructHelper.cc

Remove tracker position dependency, add wire/straw position info

---

fcl/TrkAnaExtracted.fcl
fcl/TrkAnaReco.fcl

Referring to [TrkAna/issues/169](https://github.com/Mu2e/TrkAna/issues/169):
"Attempts to set up a grid submission using TrkAna fcl files with `mu2ejobdef` will result in an error relating to the fact that `physics.trigger_paths` and `physics.end_paths` are not defined."
I've added trigger_paths and end_paths to `TrkAnaExtracted.fcl` and `TrkAnaReco.fcl`. I know that this works for these files. 
There are cases where the best way to handle this is not clear to me, such in `TrkAnaReco_wTrkQualFilter.fcl` where there are two trigger paths (TrkAnaTrigPath and TrkAnaNegTrigPath), which is why I've limited this PR to the two files stated above. 
-Sam

Added trigger_paths and end_paths to TrkAnaExtracted.fcl and TrkAnaReco.fcl 

---

fcl/TrkAnaDeMFromDigis.fcl
fcl/TrkAnaLineFromDigis.fcl
fcl/prolog.fcl
fcl/prolog_trigger.fcl
src/TrkAnaTreeMaker_module.cc

As explained in issue #164, this use of a common "suffix" to identify collections that belong together is a bit confusing. This PR removes it. I've tested TrkAnaReco.fcl and TrkAnaTriggerMCFromDigis.fcl; both still work and produce perfect matches in the validation.

Remove the "suffix" concept

---

fcl/prolog.fcl

When I removed the "suffix" concept in #164, I didn't correct the configuration for TrkAnaExtracted.fcl correctly. This PR fixes that

Fix TrkAnaExtracted error 

---

inc/TrkInfo.hh
src/InfoStructHelper.cc

This PR adds back the old track parameters to the ```demlh``` branch: ```d0``` and ```tanDip```.
Note that the ```d0``` added here is unsigned. I don't think this is an issue because the most recent sensitivity update used the magnitude of the signed ```d0``` for a cut.
Also note that these are just a stopgap until we have proper physical variables that can be used in the analysis. I will add an issue so that we remove them at some point in the future

Add old track fit parameters to LoopHelixInfo as a stopgap

---

fcl/TrkAnaReco.fcl
fcl/TrkAnaRecoEnsemble-Data.fcl
fcl/prolog.fcl
src/TrkAnaTreeMaker_module.cc

This PR makes updates so that we can run on data-only files. This has been tested by using StripMC.fcl on an mcs ensemble file. Both TrkAnaReco.fcl and TrkAnaRecoEnsemble-Data.fcl work as expected

Updates so that we can run on data-only files

---

utils/pyutils/mu2epyutil.py

This class contains functions to print the contents of an Awkward array in a human-readable form. These functions are  called `PrintNEvents` and `PrintEvent`, which work by looping through the events and then recursively searching the event array for fields and subfields. 
I have found this to be extremely useful for developing cuts and for inspecting particular events. 
**Raw Awkward array (not readable):**
```
>>> print(array_) 
`[{run: 1202, subrun: 52, event: 9989, 'crvcoincs.sectorType': [3], ...}, ...]`
```
**Human readable, one event:**
```
>>> from mu2epyutil import Print  
>>> pr = Print()
>>> pr.PrintNEvents(array_, n=1)
-------------------------------------------------------------------------------------
run: 1202
subrun: 52
event: 9989
crvcoincs.sectorType: [3] …
```

Added the "Print" class to "mu2epyutils.py"

---

fcl/from_mcs-ceSimReco.fcl
fcl/prolog.fcl

New datasets MDC202an are being created with the new APR output (see #237). These are charge agnostic and so KalSeedCollection names have changed from "KKDeM"/"KKDeP" to a single "KKDe".
This PR updates the EventNtuple configuration to write these to the EventNtuple and is backwards compatible with previous datasets.
I have tested on 10 events in the following two datasets:
* mcs.mu2e.CeEndpointMix1BBTriggered.MDC2020am_best_v1_3.art (non-APR output)
* mcs.mu2e.CeEndpointMix1BBTriggered.MDC2020an_perfect_v1_3.art (APR output)
and both produce sensible output containing tracks.
I also performed the validation steps. Updates were needed to ```fcl/from_mcs-ceSimReco.fcl``` so that everything passed

Handle APR outputs

---

utils/rooutil/inc/Event.hh
utils/rooutil/inc/RooUtil.hh

Natalie found a bug in the ```CreateNtuple.C``` example that was due to not dealing with some of the branches when creating output ntuples. This PR fixes that. Here is the output showing that it is now working:
```
root [2] ntuple->Scan("@trk.size():@trksegs.size()")
************************************
*    Row   * @trk.size * @trksegs. *
************************************
*        0 *         1 *         1 *
*        1 *         1 *         1 *
*        2 *         1 *         1 *
*        3 *         1 *         1 *
*        4 *         1 *         1 *
```

Fix missing branches for creating reduced ntuples

---

example-analysis-scripts/pyutils-examples/example_plotting.py
utils/pyutils/pyplot.py
utils/pyutils/pyprint.py

Tidied up the methods and added the functionality to pass user defined axes to the plotting functions for improved flexibility. 
I also added docstrings to the functions in the `Print` and `Plot` classes, which can be accessed as follows:
```
>>> import pyplot as plot
>>> plotter = plot.Plot()
>>> help(plotter.Plot1D)
(current) [sgrant@mu2egpvm02 pyutils-examples]$ git push fork sgrant/pyutils-dev
Help on method Plot1D in module pyplot:
Plot1D(array, nbins=100, xmin=-1.0, xmax=1.0, weights=None, title=None, xlabel=None, ylabel=None, col='black', leg_pos='best', out_path=None, dpi=300, log_x=False, log_y=False, under_over=False, stat_box=True, stat_box_errors=False, error_bars=False, ax=None, show=True) method of pyplot.Plot instance
Create a 1D histogram from an array of values.
Args: …
```

Updated methods and examples, added docstrings to Print and Plot classes

---

src/CrvInfoHelper.cc
utils/rooutil/examples/PlotGenCosmicMom.C
utils/rooutil/inc/common_cuts.hh
validation/test_rooutil_examples.sh

@oksuzian pointed out that we are missing ```GenId::cosmicCORSIKA``` in the ```CrvInfoHelper``` check. Looking into it, there is already a ```GenId::isCosmic()``` function in Offline that I will expand in a separate PR.
I have also added a new RooUtil common_cuts function to use ```GenId::isCosmic``` along with an example script.

Cosmic genids

---

README.md
bin/checkEventNtuple
src/EventNtupleMaker_module.cc
src/InfoMCStructHelper.cc
utils/rooutil/inc/Event.hh
utils/rooutil/inc/RooUtil.hh
utils/rooutil/inc/Track.hh

This PR adds a histogram to the output of EventNtuple that records the version number of EventNtuple. It also includes a command-line utility to check the version number ```checkEventNtuple```. RooUtil also records this version number. The README has also been updated with relevant information

Add versioning + RooUtil: branch protections, debug messages

---

fcl/from_mcs-ceSimReco.fcl

This had the old ```de``` name so I've changed it to ```trk``` so it can be analyzed with RooUtil

Rename branch in EventNtuple from ceSimReco

---

fcl/README.md
fcl/from_rec-crv-vst.fcl
src/EventNtupleMaker_module.cc
validation/test_fcls.sh

This PR adds a fhicl file that creates an EventNtuple on the CRV VST data.
Since the CRV VST data does not contain the ```mu2e::RecoCount``` or ```mu2e::ProtonBunchTime``` data products, I added the ability to skip those ```event.get()``` calls in the art module. To use this in future, set an empty input tag (```""```) in the fhicl configuration. I ran the validation (including ```valCompare```) and these changes do not affect previously-existing fhicl files

EventNtuple for CRV VST + Skip RecoCount and ProtonBunchTime data products

---

utils/rooutil/examples/CreateTrackNtuple.C
utils/rooutil/examples/PlotCRVTotalPEs.C
utils/rooutil/inc/Event.hh
validation/test_rooutil_examples.sh

A couple of fixes needed so that RooUtil can run on the CRV-only EventNtuples

RooUtil fixes for CRV-only EventNtuples

---

fcl/from_rec-crv-vst.fcl
src/EventNtupleMaker_module.cc
validation/test_fcls.sh

This is for the CRV VST data and also shows the way forward for issue #256 . I've also added the fhicl file that exercises the equivalent option for the tracker. Validation passes

Add option to only write events when there is CRV data

---

utils/rooutil/examples/PlotEntranceMomentum_UpstreamDownstream.C
utils/rooutil/inc/common_cuts.hh
validation/test_rooutil_examples.sh

I've added cut functions for selecting downstream and upstream tracks to the RooUtil common_cuts.hh file. I've also added an example script to the examples directory

Add downstream and upstream track cuts to RooUtil

---

helper/ntuplehelper.py
validation/ntuplehelper-test.py

This PR fixes a bug in ntuplehelper where some variables were missing from the output when the wildcard was used (```ntuplehelper branchname.*```).
This was because I had been assuming that default values were being set like:
```
type variable = value;
```
in the info struct files when searching for lines to print. However, this is not always the case.

Fix ntuplehelper bug related to wildcards

---

rooutil/README.md
rooutil/examples/PlotCaloClusterEnergy.C
rooutil/examples/PrintEvents.C
rooutil/inc/CaloCluster.hh
rooutil/inc/Event.hh
rooutil/inc/RooUtil.hh
validation/create_val_file_rooutil.C

This PR adds the new calorimeter branches to RooUtil. These can be accessed in the general ```event->branch.leaf``` way
It also adds a ```CaloCluster``` analyzer-friendly class, which only contains a link to a calorimeter cluster. It does not yet help analyzers access the underlying hits etc.

Add new calo branches to RooUtil

---

rooutil/inc/common_cuts.hh

Generic class to take a list of cuts and nevents passing each and formulate a cut flow table similar to that in pyutils
user can input any set of cuts

cutflow table generic class
