fcl/prolog.fcl
This XML file moved in Offline so we have to update it in prolog.fcl here. In the future we should think about changing TrkPID to use the AnalysisConditions infrastructure like TrkQual currently uses.
=> XML File Moved

inc/InfoMCStructHelper.hh, src/InfoMCStructHelper.cc
This fixes TrkAna following changes to the PrimaryParticle schema.
=> Follow PrimaryParticle changes

fcl/TrkAnaReco.fcl, src/TrkAnaTreeMaker_module.cc
Small fixes to align with MDC2020.
=> Primaryfix

examples/PyROOTRDataFrame.py, examples/ROOTCommandLine.C, examples/ROOTScript.C, examples/UprootScript.py
Here are a few example scripts to analyze TrkAna trees with ROOT, PyROOT and uproot. These can probably be improved (the uproot one in particular) so feel free to update them and put in a PR :)
This should close issue #18
=> TrkAna Examples

fcl/prolog.fcl, src/TrkAnaTreeMaker_module.cc
I have fixed the PBI bug (issue #17) and also simplified the code. The simplifications require Mu2e/Production#80 to be merged in so that PBI objects for primary-only datasets are made.
=> Fix PBI bug and simplify code for PBI

inc/CaloClusterInfoMC.hh, inc/GenInfo.hh, inc/InfoStructHelper.hh, inc/Names.hh, inc/TrkCaloHitInfo.hh, inc/TrkInfo.hh, inc/TrkStrawHitInfo.hh, inc/TrkStrawHitInfoMC.hh, src/InfoMCStructHelper.cc, src/InfoStructHelper.cc, src/Names.cc, src/TrkAnaTreeMaker_module.cc
Follow changes in Offline related to renaming XYZVector, associated with recent SimParticle change.
=> XYZVector renaming

inc/InfoMCStructHelper.hh
Part of an include file cleanup.  Note this depends on Offline PR 566.
=> Remove '*Collection.hh" includes

fcl/prolog.fcl
Also fic prolog because the TimeMaps were missing (although I believe they are no longer used)
=> Fix prolog

src/SConscript
...to fix valJobSecondary failure
=> Remove HepPDT from link list

examples/TrkAnaUtils.C
Improve TrkAnaUtils root macro.  It now has standard default arguments and a simpler interface, requiring less typing.
=> Improvements

src/SConscript
(cherry picked from commit 3dd5f843ad227e5c99876f06a14d0e353db4f33a)
=> add cetlib to SConscript for art v3_11

examples/TrkAnaUtils.C
I've cherry-picked Dave's commits for TrkAnaUtils so it can be added to the next Musing.
=> TrkAnaUtils

src/SConscript
=> Rollback change for KinKal v2

src/SConscript
We will need to merge this in when KinKal v2 is merged into Offline
=> Changes needed for KinKal v2

CampaignConfig/mdc2020_trkana.cfg, CampaignConfig/mdc2020_trkana.ini
Test scripts for a POMs campaign on multiple data-sets
=> POMs scripts

inc/TrkCaloHitInfo.hh, inc/TrkStrawHitInfo.hh, src/InfoStructHelper.cc
Follow changes to TrkCaloHit, goes with Offline PR 867.
=> Follow TrkCalo updates

inc/TrkInfo.hh, inc/TrkStrawHitInfo.hh, src/InfoStructHelper.cc, src/TrkAnaTreeMaker_module.cc
Add leafs for new KalSeed info.  Protect against noMC configuration missing recocount info.
=> Follow Updates

fcl/TrkAnaReco_Upstream.fcl
This fixes the issue where CRV information wasn't being written out with TrkAnaReco_Upstream.fcl
=> Fix TrkAnaReco_Upstream fcl 

inc/TrkStrawHitInfo.hh, inc/TrkStrawHitInfoMC.hh, src/InfoMCStructHelper.cc, src/InfoStructHelper.cc
Add leafs for new variables provided in Offline PR 916.  I also started to modernize the struct initialization, all the structs should be updated similarly.
=> Additional variables related to Offline PR916

src/InfoMCStructHelper.cc, src/InfoStructHelper.cc
Fixed legacy leafs to conform to BTrk conventions for all charges and helicities
=> Fix legacy leafs

inc/TrkStrawHitInfo.hh, src/InfoStructHelper.cc
This PR is linked to Offline PR 945 and should not be merged before that.
=> Add end times

fcl/TrkAnaExtracted.fcl, fcl/prolog.fcl, src/BestCrvHitDeltaT_module.cc, src/InfoMCStructHelper.cc
Fix CrvCoincidenceCluster matching to straight tracks (in Extracted reco).  Update Extracted config.
=> Crv Extracted Fix

fcl/prolog.fcl
This PR is a breaking change WRT MDC2020w and earlier production.
=> Update fcl to use KinKal fits

src/TrkAnaTreeMaker_module.cc
=> remove SimParticleTimeOffset

CampaignConfig/mdc2020_trkana.cfg, CampaignConfig/mdc2020_trkana.ini, CampaignConfig/mdc2020_trkana_split.ini
Some changes to the POMs scripts for TrkAna
=> TrkAna CFG files for POMs

src/InfoMCStructHelper.cc
=> remove ConditionsSevice AcceleratorParams

inc/TrkCaloHitInfo.hh, src/InfoStructHelper.cc
Add leafs corresponding to new payload in TrkCaloHitSeed.  Note that this requires Offline  v10_25_00 or later.
=> Update TrkCaloHit Info

inc/EventInfo.hh, inc/HitCount.hh, inc/TrkInfo.hh, src/InfoStructHelper.cc
Note the global hit struct is unfilled, that code got lost in some recent update.  The global track count also is unfilled.
=> Update count structs

tutorial/pages/genealogy.md, tutorial/pages/mom-res.md, tutorial/pages/n-hits.md, tutorial/pages/reco-mom.md, tutorial/pages/start-pos.md
A patch to explicitly create histograms in ROOT and fix the ```error: use of undeclared identifier 'hist'``` error
=> Tutorial Patch

validation/create_val_file.C
This should be the final PR for v4
=> Final tweaks to validation script

fcl/TrkAnaExtracted.fcl, fcl/TrkAnaLineFromDigis.fcl
Also added script for direct digi to trkana with KKLine
=> Fixed TrkAnaExtracted

fcl/TrkAnaTriggerMC.fcl, fcl/prolog_trigger.fcl, inc/SimInfo.hh
trigger paths were condensed.  Note this is a bug fix PR as the change to mu2e_trig_config was already merged.
=> Follow changes to mu2e_trig_config

src/TrkAnaTreeMaker_module.cc, tutorial/README.md, tutorial/pages/makeclass.md
=> Fix to get MakeClass to work

fcl/TrkAnaTriggerMC.fcl, fcl/prolog_trigger.fcl
This PR fixes a naming problem
=> Fix Apr names

fcl/TrkAnaDeMFromDigis.fcl
This PR updates prolog to follow Oflfine changes.  It is tied to [Offline PR 1287 ](https://github.com/Mu2e/Offline/pull/1287)and shouldn't be merged before that.
=> Follow KalSeedMerger changes in Offline

example-analysis-scripts/TrkAnaLoop_wCRV.C
I meant to commit this a while ago
=> Adding example TrkAna loop script with CRV info

fcl/TrkAnaDeMFromDigis.fcl, fcl/prolog.fcl
=> Follow changes in TrkConfig

inc/TrkInfo.hh, src/TrkAnaTreeMaker_module.cc
=> Follow move of SurfaceId

fcl/TrkAnaTriggerMCFromDigis.fcl
This script avoid the large intermediate file created by the sequence mu2e_trig_config/test/triggerTestMC.fcl follolwed by TrkAna/fcl/TrkAnaTriggerMC.fcl, and produces the same TrkAna output
=> Add script to process digis directly using the trigger

fcl/TrkAnaTriggerMCFromDigis.fcl
Extend the output to include trees for each of the highp trigger lines.
=> Add all highp trigger lines

fcl/TrkAnaDeMFromDigis.fcl
Also replace specific database config with comments.
=> Fix script to add SurfaceSteps

example-analysis-scripts/PythonScript.py, tutorial/pages/genealogy.md, tutorial/pages/setup.md
Pyana no longer works and so I have removed it from the tutorial
=> Remove references to pyana in tutorial

src/TrkAnaTreeMaker_module.cc
This fixes #173. I see no other errors in clang-tidy
=> Add missing overrides

fcl/prolog.fcl
Should be merged after Mu2e/Offline#1347
=> Follow-on updates for TrackQuality KalSeed --> KalSeedPtr change

fcl/from_dig-mockdata.fcl, fcl/prolog.fcl, utils/rooutil/README.md, utils/rooutil/draft.md, utils/rooutil/examples/TrackCounting.C, utils/rooutil/inc/Event.hh, utils/rooutil/inc/Track.hh, utils/rooutil/inc/TrackSegment.hh
Currently doesn't run against head of Offline so merging this in
=> Fixes for v06-dev branch

fcl/TrkAnaReflections.fcl
Also reduce verbosity of reflection selection. This is a test that old forks can be used to create PRs to the new repo name.
=> Add cosmic livetime print

README.md, fcl/README.md, utils/rooutil/README.md
Updating documentaiton a little bit
=> Readme update

fcl/README.md
Adding information on difference between mockdata and non-mockdata fcl files. Also documenting fcl files that were updated in #226
=> Updating fcl documentation

doc/ntuplehelper.md, doc/v5-to-v6.md
* added to list of branch name changes in v5-to-v6.md
* renamed in ntuplehelper examples
=> Documentatation fixes related to old demmcsim branch

src/CrvInfoHelper.cc
Related to change in CrvDigi in Mu2e/Offline#1368
=> Fix build failure in nightly

example-analysis-scripts/PlotDemo.py, example-analysis-scripts/PrintDemo.py, utils/pyutils/mu2epyutil.py
1. Added functions to the `mu2epyutils` `Plot` class, including functions for: calculating statistics for 1D histograms; plotting 1D histograms; overlaying 1D histograms; plotting 2D histograms; plotting graphs; and overlaying graphs. I have tried to use a consistent and (I think/hope) nice looking formatting and have tried to make them as flexible as possible. 
2. Added demo scripts for the `Print`and Plot() class: `PrintDemo.py` and `PlotDemo.py`. `PlotDemo.py` in particular is more-or-less a tutorial for the `Plot()` class, showing what each function can do. 
Here the plots the `PlotDemo.py` generates:
=> Added functions to the mu2epyutils Plot class and added demo scripts for Print and Plot classes

fcl/from_dig-OnSpill.fcl, fcl/prolog.fcl
These were missed in the first PR.
=> Add other track trigger paths to the digi tuple making

src/InfoMCStructHelper.cc
an attempt to fix https://github.com/Mu2e/EventNtuple/issues/229
=> Remove duplicate particles from trksegmc

fcl/from_dig-mockdata.fcl, validation/test_fcls.sh
The ```test_fcls.sh``` script was failing for two reasons:
* needed updated datasets, and
* needed updates to the ```from_dig-mockdata.fcl``` file due to changes in upstream prolog
I also updated the script to use ```mu2eDatasetFileList``` instead of ```samListLocations```
=> Fixes for Validation

fcl/prolog.fcl
Correcting inadvertant change in prolog
=> Redo prolog change

fcl/from_dig-DeCalib.fcl, fcl/from_mcs-reflection.fcl, fcl/prolog.fcl
Also added a filter to remove empty events from DeCalib
=> Add TrkQual to reflections

fcl/from_dig-DeCalib_seed.fcl, inc/TrkStrawMatInfo.hh, src/InfoStructHelper.cc
These changes depend on Offline PR 1571. They are a pure addition, should not break against any existing data.
=> Add info about straw material

doc/branches.md, fcl/prolog.fcl, helper/ntuplehelper.py, inc/InfoStructHelper.hh, inc/TrkInfo.hh, inc/TrkStrawHitCalibInfo.hh, inc/TrkStrawHitInfo.hh, src/EventNtupleMaker_module.cc, src/InfoStructHelper.cc, src/classes.h, src/classes_def.xml
=> Added hit calib info

fcl/from_mcs-ceSimReco.fcl, fcl/prolog.fcl, rooutil/README.md, rooutil/examples/PlotTrackHitCalibs.C, rooutil/examples/PrintEvents.C, rooutil/inc/Event.hh, rooutil/inc/RooUtil.hh, rooutil/inc/Track.hh, rooutil/inc/TrackHit.hh, src/InfoStructHelper.cc, validation/ceSimReco.fcl, validation/create_val_file_rooutil.C, validation/test_fcls.sh
Following on from #301, I have added tests of the trkhitcalibs branch to the validation and to RooUtil
=> Add trkhitcalibs branch to validation and RooUtil
